# Generated by Django 5.2 on 2025-05-04 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0003_firm_alter_customuser_id_customuser_firm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='secret_key',
            new_name='mfa_secret_key',
        ),
    ]
