# Generated by Django 5.2 on 2025-05-04 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0004_rename_secret_key_customuser_mfa_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='majorApp.firm'),
        ),
    ]
