# Generated by Django 5.2 on 2025-05-04 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0007_contact_alter_firm_name_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='firm',
            field=models.ForeignKey(default='b729a5c3-936b-4aa0-9a17-269663997b34', on_delete=django.db.models.deletion.CASCADE, to='majorApp.firm'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('A', 'a'), ('B', 'b')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majorApp.company')),
                ('contacts', models.ManyToManyField(to='majorApp.contact')),
            ],
        ),
    ]
