# Generated by Django 5.2 on 2025-05-04 05:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0008_contact_firm_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majorApp.company')),
                ('contacts', models.ManyToManyField(to='majorApp.contact')),
                ('lead', models.ForeignKey(blank=True, help_text='Optional to Link to a Lead', null=True, on_delete=django.db.models.deletion.CASCADE, to='majorApp.lead')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majorApp.quote')),
            ],
        ),
    ]
