# Generated by Django 5.2 on 2025-05-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0009_quote_quoteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NC', 'Not Contacted'), ('IC', 'Initial Contact Made'), ('QS', 'Quote Sent'), ('C', 'Converted'), ('DNC', 'Do Not Contact')], max_length=50),
        ),
    ]
