# Generated by Django 5.2 on 2025-05-04 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0010_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(default=datetime.date(2025, 5, 4)),
        ),
    ]
