# Generated by Django 5.2 on 2025-05-04 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0011_lead_last_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 4), null=True),
        ),
    ]
