# Generated by Django 5.2 on 2025-05-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0012_alter_lead_last_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('S', 'Sent'), ('W', 'Won'), ('L', 'Lost')], default='W', max_length=50),
            preserve_default=False,
        ),
    ]
