# Generated by Django 5.2 on 2025-05-04 06:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0013_quote_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('D', 'Draft'), ('S', 'Sent'), ('W', 'Won'), ('L', 'Lost')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majorApp.company')),
                ('contacts', models.ManyToManyField(to='majorApp.contact')),
                ('lead', models.ForeignKey(blank=True, help_text='Optional to Link to a Lead', null=True, on_delete=django.db.models.deletion.CASCADE, to='majorApp.lead')),
                ('quote', models.ForeignKey(blank=True, help_text='Optional to Link to a Quote', null=True, on_delete=django.db.models.deletion.CASCADE, to='majorApp.quote')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='majorApp.invoice')),
            ],
        ),
    ]
