# Generated by Django 5.2 on 2025-05-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0014_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('S', 'Sent')], max_length=50),
        ),
    ]
