# Generated by Django 5.2 on 2025-05-06 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0015_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 6), null=True),
        ),
    ]
