# Generated by Django 5.2 on 2025-05-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0017_alter_company_address_alter_company_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to='majorApp.contact'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to='majorApp.contact'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, to='majorApp.contact'),
        ),
    ]
