# Generated by Django 5.2 on 2025-05-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0018_alter_invoice_contacts_alter_lead_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('S', 'Sent'), ('W', 'Won'), ('L', 'Lost')], max_length=50),
        ),
    ]
