# Generated by Django 5.2 on 2025-05-26 08:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0019_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='lead',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='quote',
            field=models.ForeignKey(blank=True, help_text='Optional to Link to a Quote', null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorApp.quote'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 26), null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Optional to Link to a Lead', null=True, on_delete=django.db.models.deletion.SET_NULL, to='majorApp.lead'),
        ),
    ]
