# Generated by Django 5.2 on 2025-05-27 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0020_remove_invoice_lead_alter_invoice_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 27), null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 27), null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 5, 27), null=True),
        ),
    ]
