# Generated by Django 5.2 on 2025-05-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0021_invoice_last_contact_date_quote_last_contact_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(related_name='companies', to='majorApp.contact'),
        ),
    ]
