# Generated by Django 5.2 on 2025-05-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0022_alter_company_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='companies', to='majorApp.contact'),
        ),
    ]
