# Generated by Django 5.2 on 2025-06-05 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0023_alter_company_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 6), null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 6), null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 6), null=True),
        ),
    ]
