# Generated by Django 5.2 on 2025-06-09 05:19

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0025_quoteitem_created_at_alter_invoice_last_contact_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 9), null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 9), null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 9), null=True),
        ),
    ]
