# Generated by Django 5.2 on 2025-06-09 23:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0026_invoiceitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 10), null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 10), null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 10), null=True),
        ),
    ]
