# Generated by Django 5.2 on 2025-06-11 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0027_alter_invoice_last_contact_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 11), null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 11), null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 11), null=True),
        ),
    ]
