# Generated by Django 5.2 on 2025-06-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0029_company_industry_alter_invoice_last_contact_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='title',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
