# Generated by Django 5.2 on 2025-06-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0030_quoteitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='invoice_index',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firm',
            name='quote_index',
            field=models.SmallIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
