# Generated by Django 5.2 on 2025-06-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0031_firm_invoice_index_firm_quote_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
