# Generated by Django 5.2 on 2025-06-16 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0033_alter_contact_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='title',
        ),
    ]
