# Generated by Django 5.2 on 2025-06-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0034_remove_quoteitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_index',
            field=models.SmallIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
