# Generated by Django 5.2 on 2025-06-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0035_quote_quote_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_index',
            field=models.SmallIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
