# Generated by Django 5.2 on 2025-06-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0036_invoice_invoice_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='invoice_index',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='firm',
            name='quote_index',
            field=models.SmallIntegerField(default=0),
        ),
    ]
