# Generated by Django 5.2 on 2025-06-18 01:03

import datetime
import majorApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0037_alter_firm_invoice_index_alter_firm_quote_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.TextField(max_length=30, validators=[majorApp.models.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.TextField(blank=True, max_length=20, validators=[majorApp.models.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.TextField(blank=True, max_length=20, validators=[majorApp.models.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.TextField(max_length=30, validators=[majorApp.models.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 18), null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 18), null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='last_contact_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 6, 18), null=True),
        ),
    ]
