# Generated by Django 5.2 on 2025-06-18 01:06

import majorApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorApp', '0038_alter_company_name_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=25, validators=[majorApp.models.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=25, validators=[majorApp.models.validate_letters_only]),
        ),
    ]
