services:
  web:
    container_name: web
    restart: always
    # environment:
    #   - DJANGO_DEBUG=True
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"

    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]